### ISSUE TITLE
取り組みの方針

### ISSUE THREAD

**Issue by Rintan** [GenbuProject/Minecraft-Colonies-Shell#1]
修正したいのでメモ
PageSpeed Insights

[モバイル](https://developers.google.com/speed/pagespeed/insights/?hl=ja&url=https%3A%2F%2Fgenbuproject.github.io%2FMinecraft-Colonies-Shell%2F&tab=mobile)

[PC](https://developers.google.com/speed/pagespeed/insights/?hl=ja&url=https%3A%2F%2Fgenbuproject.github.io%2FMinecraft-Colonies-Shell%2F&tab=desktop)

**Comment by GenbuHase** [comment]
承知です。ありがとう。

**Comment by GenbuHase** [comment]
IFrameに切り替えました。
パフォーマンスの改善はこれからの予定です。

**Comment by Rintan** [comment]
@GenbuHase 了解です！
